global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'restaurant-service'
    static_configs:
      - targets: ['restaurant-service:80']

  - job_name: 'amenity-service'
    static_configs:
      - targets: ['amenity-service:80']
